server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spring-integration-example
  
  # Logging configuration
  logging:
    level:
      com.example.spring: DEBUG
      com.flexiblesdk: DEBUG
      org.springframework: INFO
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: logs/spring-integration.log

  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: always

# Custom application properties
app:
  name: "FlexibleSDK Spring Integration Example"
  version: "1.0.0"
  description: "Demonstrates integration between Spring Framework and FlexibleSDK Processor"